### ISSUE TITLE
Add a .editorconfig file

### ISSUE THREAD

**Issue by peter-r-g** [mocha-engine/mocha2#3]
While working on #2 VS2022 was getting very confused about formatting and it required me to do dotnet formats and manual switching between indent styles. I suggest getting an editor config file in so it is handled automatically.

**Comment by xezno** [comment]
Yeah I noticed this last night :pensive:

**Comment by xezno** [comment]
Fixed with 79e9732611c97cee63502f871d881cb2380a73a4
